apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
