apiVersion: v1
kind: Service
metadata:
  name: patient
spec:
  type: {{ .Values.service.type }}
  selector:
    app: patient
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
